/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VyborOborudovaniyaDlyaLvsRouteImport } from './routes/vybor-oborudovaniya-dlya-lvs'
import { Route as VpsRouteImport } from './routes/vps'
import { Route as ThankYouRouteImport } from './routes/thank-you'
import { Route as SpamRouteImport } from './routes/spam'
import { Route as RequisitesRouteImport } from './routes/requisites'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OshibkiPriMontazheSksRouteImport } from './routes/oshibki-pri-montazhe-sks'
import { Route as ObjectStorageRouteImport } from './routes/object-storage'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KakPravilnoProlozhitKabelRouteImport } from './routes/kak-pravilno-prolozhit-kabel'
import { Route as ItSksRouteImport } from './routes/it-sks'
import { Route as ItRouteImport } from './routes/it'
import { Route as InternetRouteImport } from './routes/internet'
import { Route as IaasRouteImport } from './routes/iaas'
import { Route as HrRouteImport } from './routes/hr'
import { Route as DedicatedRouteImport } from './routes/dedicated'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as ColocationFullRouteImport } from './routes/colocation-full'
import { Route as ColocationRouteImport } from './routes/colocation'
import { Route as CloudStorageRouteImport } from './routes/cloud-storage'
import { Route as CloudRouteImport } from './routes/cloud'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const VyborOborudovaniyaDlyaLvsRoute =
  VyborOborudovaniyaDlyaLvsRouteImport.update({
    id: '/vybor-oborudovaniya-dlya-lvs',
    path: '/vybor-oborudovaniya-dlya-lvs',
    getParentRoute: () => rootRouteImport,
  } as any)
const VpsRoute = VpsRouteImport.update({
  id: '/vps',
  path: '/vps',
  getParentRoute: () => rootRouteImport,
} as any)
const ThankYouRoute = ThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const SpamRoute = SpamRouteImport.update({
  id: '/spam',
  path: '/spam',
  getParentRoute: () => rootRouteImport,
} as any)
const RequisitesRoute = RequisitesRouteImport.update({
  id: '/requisites',
  path: '/requisites',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OshibkiPriMontazheSksRoute = OshibkiPriMontazheSksRouteImport.update({
  id: '/oshibki-pri-montazhe-sks',
  path: '/oshibki-pri-montazhe-sks',
  getParentRoute: () => rootRouteImport,
} as any)
const ObjectStorageRoute = ObjectStorageRouteImport.update({
  id: '/object-storage',
  path: '/object-storage',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KakPravilnoProlozhitKabelRoute =
  KakPravilnoProlozhitKabelRouteImport.update({
    id: '/kak-pravilno-prolozhit-kabel',
    path: '/kak-pravilno-prolozhit-kabel',
    getParentRoute: () => rootRouteImport,
  } as any)
const ItSksRoute = ItSksRouteImport.update({
  id: '/it-sks',
  path: '/it-sks',
  getParentRoute: () => rootRouteImport,
} as any)
const ItRoute = ItRouteImport.update({
  id: '/it',
  path: '/it',
  getParentRoute: () => rootRouteImport,
} as any)
const InternetRoute = InternetRouteImport.update({
  id: '/internet',
  path: '/internet',
  getParentRoute: () => rootRouteImport,
} as any)
const IaasRoute = IaasRouteImport.update({
  id: '/iaas',
  path: '/iaas',
  getParentRoute: () => rootRouteImport,
} as any)
const HrRoute = HrRouteImport.update({
  id: '/hr',
  path: '/hr',
  getParentRoute: () => rootRouteImport,
} as any)
const DedicatedRoute = DedicatedRouteImport.update({
  id: '/dedicated',
  path: '/dedicated',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const ColocationFullRoute = ColocationFullRouteImport.update({
  id: '/colocation-full',
  path: '/colocation-full',
  getParentRoute: () => rootRouteImport,
} as any)
const ColocationRoute = ColocationRouteImport.update({
  id: '/colocation',
  path: '/colocation',
  getParentRoute: () => rootRouteImport,
} as any)
const CloudStorageRoute = CloudStorageRouteImport.update({
  id: '/cloud-storage',
  path: '/cloud-storage',
  getParentRoute: () => rootRouteImport,
} as any)
const CloudRoute = CloudRouteImport.update({
  id: '/cloud',
  path: '/cloud',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cloud': typeof CloudRoute
  '/cloud-storage': typeof CloudStorageRoute
  '/colocation': typeof ColocationRoute
  '/colocation-full': typeof ColocationFullRoute
  '/contacts': typeof ContactsRoute
  '/dedicated': typeof DedicatedRoute
  '/hr': typeof HrRoute
  '/iaas': typeof IaasRoute
  '/internet': typeof InternetRoute
  '/it': typeof ItRoute
  '/it-sks': typeof ItSksRoute
  '/kak-pravilno-prolozhit-kabel': typeof KakPravilnoProlozhitKabelRoute
  '/login': typeof LoginRoute
  '/object-storage': typeof ObjectStorageRoute
  '/oshibki-pri-montazhe-sks': typeof OshibkiPriMontazheSksRoute
  '/privacy': typeof PrivacyRoute
  '/requisites': typeof RequisitesRoute
  '/spam': typeof SpamRoute
  '/thank-you': typeof ThankYouRoute
  '/vps': typeof VpsRoute
  '/vybor-oborudovaniya-dlya-lvs': typeof VyborOborudovaniyaDlyaLvsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cloud': typeof CloudRoute
  '/cloud-storage': typeof CloudStorageRoute
  '/colocation': typeof ColocationRoute
  '/colocation-full': typeof ColocationFullRoute
  '/contacts': typeof ContactsRoute
  '/dedicated': typeof DedicatedRoute
  '/hr': typeof HrRoute
  '/iaas': typeof IaasRoute
  '/internet': typeof InternetRoute
  '/it': typeof ItRoute
  '/it-sks': typeof ItSksRoute
  '/kak-pravilno-prolozhit-kabel': typeof KakPravilnoProlozhitKabelRoute
  '/login': typeof LoginRoute
  '/object-storage': typeof ObjectStorageRoute
  '/oshibki-pri-montazhe-sks': typeof OshibkiPriMontazheSksRoute
  '/privacy': typeof PrivacyRoute
  '/requisites': typeof RequisitesRoute
  '/spam': typeof SpamRoute
  '/thank-you': typeof ThankYouRoute
  '/vps': typeof VpsRoute
  '/vybor-oborudovaniya-dlya-lvs': typeof VyborOborudovaniyaDlyaLvsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cloud': typeof CloudRoute
  '/cloud-storage': typeof CloudStorageRoute
  '/colocation': typeof ColocationRoute
  '/colocation-full': typeof ColocationFullRoute
  '/contacts': typeof ContactsRoute
  '/dedicated': typeof DedicatedRoute
  '/hr': typeof HrRoute
  '/iaas': typeof IaasRoute
  '/internet': typeof InternetRoute
  '/it': typeof ItRoute
  '/it-sks': typeof ItSksRoute
  '/kak-pravilno-prolozhit-kabel': typeof KakPravilnoProlozhitKabelRoute
  '/login': typeof LoginRoute
  '/object-storage': typeof ObjectStorageRoute
  '/oshibki-pri-montazhe-sks': typeof OshibkiPriMontazheSksRoute
  '/privacy': typeof PrivacyRoute
  '/requisites': typeof RequisitesRoute
  '/spam': typeof SpamRoute
  '/thank-you': typeof ThankYouRoute
  '/vps': typeof VpsRoute
  '/vybor-oborudovaniya-dlya-lvs': typeof VyborOborudovaniyaDlyaLvsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cloud'
    | '/cloud-storage'
    | '/colocation'
    | '/colocation-full'
    | '/contacts'
    | '/dedicated'
    | '/hr'
    | '/iaas'
    | '/internet'
    | '/it'
    | '/it-sks'
    | '/kak-pravilno-prolozhit-kabel'
    | '/login'
    | '/object-storage'
    | '/oshibki-pri-montazhe-sks'
    | '/privacy'
    | '/requisites'
    | '/spam'
    | '/thank-you'
    | '/vps'
    | '/vybor-oborudovaniya-dlya-lvs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cloud'
    | '/cloud-storage'
    | '/colocation'
    | '/colocation-full'
    | '/contacts'
    | '/dedicated'
    | '/hr'
    | '/iaas'
    | '/internet'
    | '/it'
    | '/it-sks'
    | '/kak-pravilno-prolozhit-kabel'
    | '/login'
    | '/object-storage'
    | '/oshibki-pri-montazhe-sks'
    | '/privacy'
    | '/requisites'
    | '/spam'
    | '/thank-you'
    | '/vps'
    | '/vybor-oborudovaniya-dlya-lvs'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/cloud'
    | '/cloud-storage'
    | '/colocation'
    | '/colocation-full'
    | '/contacts'
    | '/dedicated'
    | '/hr'
    | '/iaas'
    | '/internet'
    | '/it'
    | '/it-sks'
    | '/kak-pravilno-prolozhit-kabel'
    | '/login'
    | '/object-storage'
    | '/oshibki-pri-montazhe-sks'
    | '/privacy'
    | '/requisites'
    | '/spam'
    | '/thank-you'
    | '/vps'
    | '/vybor-oborudovaniya-dlya-lvs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CloudRoute: typeof CloudRoute
  CloudStorageRoute: typeof CloudStorageRoute
  ColocationRoute: typeof ColocationRoute
  ColocationFullRoute: typeof ColocationFullRoute
  ContactsRoute: typeof ContactsRoute
  DedicatedRoute: typeof DedicatedRoute
  HrRoute: typeof HrRoute
  IaasRoute: typeof IaasRoute
  InternetRoute: typeof InternetRoute
  ItRoute: typeof ItRoute
  ItSksRoute: typeof ItSksRoute
  KakPravilnoProlozhitKabelRoute: typeof KakPravilnoProlozhitKabelRoute
  LoginRoute: typeof LoginRoute
  ObjectStorageRoute: typeof ObjectStorageRoute
  OshibkiPriMontazheSksRoute: typeof OshibkiPriMontazheSksRoute
  PrivacyRoute: typeof PrivacyRoute
  RequisitesRoute: typeof RequisitesRoute
  SpamRoute: typeof SpamRoute
  ThankYouRoute: typeof ThankYouRoute
  VpsRoute: typeof VpsRoute
  VyborOborudovaniyaDlyaLvsRoute: typeof VyborOborudovaniyaDlyaLvsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vybor-oborudovaniya-dlya-lvs': {
      id: '/vybor-oborudovaniya-dlya-lvs'
      path: '/vybor-oborudovaniya-dlya-lvs'
      fullPath: '/vybor-oborudovaniya-dlya-lvs'
      preLoaderRoute: typeof VyborOborudovaniyaDlyaLvsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vps': {
      id: '/vps'
      path: '/vps'
      fullPath: '/vps'
      preLoaderRoute: typeof VpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thank-you': {
      id: '/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof ThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spam': {
      id: '/spam'
      path: '/spam'
      fullPath: '/spam'
      preLoaderRoute: typeof SpamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requisites': {
      id: '/requisites'
      path: '/requisites'
      fullPath: '/requisites'
      preLoaderRoute: typeof RequisitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oshibki-pri-montazhe-sks': {
      id: '/oshibki-pri-montazhe-sks'
      path: '/oshibki-pri-montazhe-sks'
      fullPath: '/oshibki-pri-montazhe-sks'
      preLoaderRoute: typeof OshibkiPriMontazheSksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/object-storage': {
      id: '/object-storage'
      path: '/object-storage'
      fullPath: '/object-storage'
      preLoaderRoute: typeof ObjectStorageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kak-pravilno-prolozhit-kabel': {
      id: '/kak-pravilno-prolozhit-kabel'
      path: '/kak-pravilno-prolozhit-kabel'
      fullPath: '/kak-pravilno-prolozhit-kabel'
      preLoaderRoute: typeof KakPravilnoProlozhitKabelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/it-sks': {
      id: '/it-sks'
      path: '/it-sks'
      fullPath: '/it-sks'
      preLoaderRoute: typeof ItSksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/it': {
      id: '/it'
      path: '/it'
      fullPath: '/it'
      preLoaderRoute: typeof ItRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internet': {
      id: '/internet'
      path: '/internet'
      fullPath: '/internet'
      preLoaderRoute: typeof InternetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iaas': {
      id: '/iaas'
      path: '/iaas'
      fullPath: '/iaas'
      preLoaderRoute: typeof IaasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr': {
      id: '/hr'
      path: '/hr'
      fullPath: '/hr'
      preLoaderRoute: typeof HrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dedicated': {
      id: '/dedicated'
      path: '/dedicated'
      fullPath: '/dedicated'
      preLoaderRoute: typeof DedicatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colocation-full': {
      id: '/colocation-full'
      path: '/colocation-full'
      fullPath: '/colocation-full'
      preLoaderRoute: typeof ColocationFullRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colocation': {
      id: '/colocation'
      path: '/colocation'
      fullPath: '/colocation'
      preLoaderRoute: typeof ColocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cloud-storage': {
      id: '/cloud-storage'
      path: '/cloud-storage'
      fullPath: '/cloud-storage'
      preLoaderRoute: typeof CloudStorageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cloud': {
      id: '/cloud'
      path: '/cloud'
      fullPath: '/cloud'
      preLoaderRoute: typeof CloudRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CloudRoute: CloudRoute,
  CloudStorageRoute: CloudStorageRoute,
  ColocationRoute: ColocationRoute,
  ColocationFullRoute: ColocationFullRoute,
  ContactsRoute: ContactsRoute,
  DedicatedRoute: DedicatedRoute,
  HrRoute: HrRoute,
  IaasRoute: IaasRoute,
  InternetRoute: InternetRoute,
  ItRoute: ItRoute,
  ItSksRoute: ItSksRoute,
  KakPravilnoProlozhitKabelRoute: KakPravilnoProlozhitKabelRoute,
  LoginRoute: LoginRoute,
  ObjectStorageRoute: ObjectStorageRoute,
  OshibkiPriMontazheSksRoute: OshibkiPriMontazheSksRoute,
  PrivacyRoute: PrivacyRoute,
  RequisitesRoute: RequisitesRoute,
  SpamRoute: SpamRoute,
  ThankYouRoute: ThankYouRoute,
  VpsRoute: VpsRoute,
  VyborOborudovaniyaDlyaLvsRoute: VyborOborudovaniyaDlyaLvsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
